#! /bin/sh

set -e

package_name=prelink-fix

case "$1" in
  remove)
      dpkg-divert --package $package_name --rename --remove  /etc/prelink.conf
    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0





