#! /bin/sh

set -e

package_name=systemsettings-hide
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/kdesystemsettings.desktop --rename /usr/share/applications/kde4/kdesystemsettings.desktop
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/systemsettings.desktop --rename /usr/share/applications/kde4/systemsettings.desktop
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /usr/share/applications/kde4/kdesystemsettings.desktop)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/kdesystemsettings.desktop --rename /usr/share/applications/kde4/kdesystemsettings.desktop
	fi

        if [ "$(dpkg-divert --list /usr/share/applications/kde4/systemsettings.desktop)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/systemsettings.desktop --rename /usr/share/applications/kde4/systemsettings.desktop
	fi


;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
