#! /bin/sh

set -e

package_name=bigsamba

case "$1" in
  remove)
	dpkg-divert --package bigsamba --rename --remove /etc/init/smbd.conf
	dpkg-divert --package bigsamba --rename --remove /etc/init//etc/nsswitch.conf

    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0





