#! /bin/sh

set -e

package_name=kaiana-ramcache-base

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  remove)
        rm -f /etc/rc0.d/K01kaiana-cache
	rm -f /etc/rc6.d/K01kaiana-cache 
    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
