#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Repositório com pacotes que adicionam suporte a partições exfat"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    add-apt-repository ppa:relan/exfat -y
	exit
    ;;

    --remove)
	    add-apt-repository ppa:relan/exfat -r -y
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac

