#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Adiciona o repositório do google chrome"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
	    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome-stable.list
	exit
    ;;

    --remove)
	    rm -f /etc/apt/sources.list.d/google-chrome-stable.list
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac

