#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Adiciona o repositorio do java da oracle, infelizmente o java livre não funciona muito bem em 64 bits"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    add-apt-repository ppa:webupd8team/java -y
	exit
    ;;

    --remove)
	    add-apt-repository ppa:webupd8team/java -r -y
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac
