# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("general.smoothScroll", false);
user_pref("extensions.useragentoverrider.activated", true);
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.aggressive", true);
user_pref("network.http.pipelining.ssl", true);
user_pref("network.http.proxy.pipelining", true);
user_pref("image.high_quality_downscaling.enabled", false);
user_pref("middlemouse.contentLoadURL", false);
user_pref("browser.showQuitWarning", true);
user_pref("browser.urlbar.clickSelectsAll", true);
user_pref("browser.startup.homepage", "http://start.kaiana.com.br");
user_pref("startup.homepage_welcome_url", "");
user_pref("layout.spellcheckDefault", 2);