user_pref("general.smoothScroll", false);
user_pref("extensions.useragentoverrider.activated", true);
user_pref("general.useragent.override.netflix.com", "Safari/OSX: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10"); 
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.aggressive", true);
user_pref("network.http.pipelining.ssl", true);
user_pref("network.http.proxy.pipelining", true);
user_pref("image.high_quality_downscaling.enabled", false);
user_pref("middlemouse.contentLoadURL", false);
user_pref("browser.showQuitWarning", true);
user_pref("browser.urlbar.clickSelectsAll", true);
user_pref("browser.startup.homepage", "http://start.kaiana.com.br");
user_pref("startup.homepage_welcome_url", "");
user_pref("layout.spellcheckDefault", 2);