#! /bin/sh

set -e

package_name=totem-hidden
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/totem.desktop --rename /usr/share/applications/totem.desktop
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/totem --rename /usr/share/menu/totem
    
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /usr/share/applications/totem.desktop)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/totem.desktop --rename /usr/share/applications/totem.desktop
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/totem --rename /usr/share/menu/totem
	fi

;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
