#! /bin/sh

set -e

#Nome do pacote
package_name=bigsudo

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

#Troca arquivos de outros pacotes pelos contidos nesse pacote, renomeando o do outro pacote para o mesmo nome com a inclusao da extensao .distrib
case "$1" in
  install)
      dpkg-divert --package $package_name --divert /etc/sudoers.distrib --rename /etc/sudoers
;;

  upgrade)
        if [ "$(dpkg-divert --list /etc/sudoers)" = "" ]
        then
		dpkg-divert --package $package_name --divert /etc/sudoers.distrib --rename /etc/sudoers
	fi
    ;;
esac

exit 0