#! /bin/sh

set -e

package_name=kaiananame

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  remove)
    dpkg-divert --package $package_name --rename --remove /etc/issue
    dpkg-divert --package $package_name --rename --remove /etc/issue.net
    dpkg-divert --package $package_name --rename --remove /etc/lsb-release
    dpkg-divert --package $package_name --rename --remove /etc/legal
    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
