#! /bin/sh

set -e

package_name=big-fix-kde-start
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/bin/startkde.distrib --rename /usr/bin/startkde
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /usr/bin/startkde)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/bin/startkde.distrib --rename /usr/bin/startkde
	fi

;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
