#! /bin/sh

set -e

sed -i 's|width: theme.defaultFont.mSize.width \* 18|width: theme.defaultFont.mSize.width * 24|g;s|theme.smallIconSize|20|g' /usr/share/kde4/apps/plasma/plasmoids/org.kde.homerun-kicker/contents/ui/ItemListView.qml

ln -sf /etc/init.d/homerunkickerresize /etc/rc5.d/S99homerunkickerresize
ln -sf /etc/init.d/homerunkickerresize /etc/rc4.d/S99homerunkickerresize
ln -sf /etc/init.d/homerunkickerresize /etc/rc3.d/S99homerunkickerresize
ln -sf /etc/init.d/homerunkickerresize /etc/rc2.d/S99homerunkickerresize


exit 0
