#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Adiciona o repositório com os plugins gmic do gimp"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    add-apt-repository ppa:otto-kesselgulasch/gimp -y
	exit
    ;;

    --remove)
	    add-apt-repository ppa:otto-kesselgulasch/gimp -r -y
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac
