#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Adiciona o repositorio União Livre"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    echo 'deb http://repo.uniaolivre.com/packages trusty main' > /etc/apt/sources.list.d/kaiana.list
	    wget http://repo.uniaolivre.com/uniaolivre.key -O- | apt-key add -
	exit
    ;;

    --remove)
	    rm -f /etc/apt/sources.list.d/kaiana.list
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac
