#! /bin/sh

set -e

package_name=disable-tty-autostart

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  remove)
    dpkg-divert --package $package_name --rename --remove /etc/init/tty3.conf
    dpkg-divert --package $package_name --rename --remove /etc/init/tty4.conf
    dpkg-divert --package $package_name --rename --remove /etc/init/tty5.conf
    dpkg-divert --package $package_name --rename --remove /etc/init/tty6.conf
    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
