#! /bin/sh

set -e

package_name=disable-tty-autostart
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty3.conf --rename /etc/init/tty3.conf
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty4.conf --rename /etc/init/tty4.conf
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty5.conf --rename /etc/init/tty5.conf
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty6.conf --rename /etc/init/tty6.conf
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /etc/init/tty3.conf)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty3.conf --rename /etc/init/tty3.conf
	fi

        if [ "$(dpkg-divert --list /etc/init/tty4.conf)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty4.conf --rename /etc/init/tty4.conf
	fi

        if [ "$(dpkg-divert --list /etc/init/tty5.conf)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty5.conf --rename /etc/init/tty5.conf
	fi

        if [ "$(dpkg-divert --list /etc/init/tty6.conf)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/tty6.conf --rename /etc/init/tty6.conf
	fi
	
	
;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
