#! /bin/sh

set -e

package_name=big-grubtweaks
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

update-grub

exit 0
