#!/bin/sh

set -e

package_name=k-lightdm-integration

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
	sed -i 's|greeter-session=.*|greeter-session=unity-greeter|g' /etc/lightdm/lightdm.conf
    ;;
  *) 
     exit 0;;
esac

exit 0
