#! /bin/sh

set -e

package_name=bigcontrolcenter-system-optimizes

        if [ "$(dpkg-divert --list /etc/init.d/sendsigs)" != "" ]
        then
	        rm -f /etc/init.d/sendsigs
	fi

case "$1" in
  remove)
      dpkg-divert --package $package_name --rename --remove /etc/xdg/autostart/update-notifier.desktop
      dpkg-divert --package $package_name --rename --remove /etc/init.d/sendsigs
      dpkg-divert --package $package_name --rename --remove /usr/bin/startkde
      dpkg-divert --package $package_name --rename --remove /usr/share/autostart/akonaditray.desktop
    ;;
  purge)
    ;;
  upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0


