#! /bin/sh

set -e

#Nome do pacote
package_name=bigcontrolcenter-system-optimizes

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

#Troca arquivos de outros pacotes pelos contidos nesse pacote, renomeando o do outro pacote para o mesmo nome com a inclusao da extensao .distrib

        if [ "$(dpkg-divert --list /usr/bin/startkde)" != "" ]
        then
		dpkg-divert --package bigcontrolcenter-system-optimizes --rename --remove /usr/bin/startkde
	fi


exit 0
