#!/bin/bash

#Translation
export TEXTDOMAINDIR="/usr/share/locale-langpack"
export TEXTDOMAIN=kaiana-iso-generator

repository_description=$"Adiciona suporte ao gstreamer ffmpeg para dar suporte a 264 html5 no firefox"


case "$1" in

    --description)
	    echo "$repository_description"
	exit
    ;;

    --add)
	    add-apt-repository ppa:mc3man/trusty-media -y
	exit
    ;;

    --remove)
	    add-apt-repository ppa:mc3man/trusty-media -r -y
	exit
    ;;

    *)
	echo $"--description            show details by repository"
	echo $"--add		       add repository to system remastering"
	echo $"--remove		       remove repository to system remastering"
	exit
    ;;

esac
