#! /bin/sh

set -e

package_name=big-replace-kde-polkit
mkdir -p /usr/share/dpkgdivert/

if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/polkit-kde-authentication-agent-1.desktop --rename /usr/share/autostart/polkit-kde-authentication-agent-1.desktop
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /usr/share/autostart/polkit-kde-authentication-agent-1.desktop)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/share/dpkgdivert/polkit-kde-authentication-agent-1.desktop --rename /usr/share/autostart/polkit-kde-authentication-agent-1.desktop
	fi

;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
