#! /bin/sh

set -e

package_name=kaiana-ramcache-google-chrome-beta


if [ -z "$package_name" ]; then
    print >&2 "Internal Error. Please report a bug."
    exit 1;
fi

case "$1" in
  install)
    dpkg-divert --package $package_name --divert /usr/bin/google-chrome-beta.distrib --rename /usr/bin/google-chrome-beta
    ln -sf /usr/bin/google-chrome-beta-ram /usr/bin/google-chrome-beta
    ;;
  upgrade)
        if [ "$(dpkg-divert --list /etc/init.d/sendsigs)" = "" ]
        then
	    dpkg-divert --package $package_name --divert /usr/bin/google-chrome-beta.distrib --rename /usr/bin/google-chrome-beta

	fi
;;
  abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

exit 0
